import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { checkInAction } from '@/lib/actions/events';
import { isUuid, formatEventDate } from '@/lib/events';
import { EventRegistration } from '@/types/database';
import { MutationButton } from '@/components/ActionForm';

export default async function CheckInPage({ searchParams }: { searchParams: Promise<{ token?: string }> }) {
  const { token } = await searchParams; let registration: EventRegistration | null = null; let unavailable = false;
  if (isUuid(token)) { const { data, error } = await (await createClient()).from('event_registrations').select('*, profiles(username), event_seats(table_number,seat_number), game_events(*)').eq('checkin_token',token).maybeSingle(); registration = data as EventRegistration | null; unavailable = !!error; }
  return <div className="max-w-xl mx-auto px-5"><h1 className="text-3xl font-bold mb-3">Atvykimo registracija</h1><p className="text-sm text-slate-400 mb-6">Nuskenuokite žaidėjo QR kodą telefono kamera arba įklijuokite bilieto kodą čia. Atvykimas pažymimas tik jums patvirtinus.</p><form className="panel mb-6" method="get"><label className="field-label">Bilieto kodas<input className="field mt-2" name="token" defaultValue={token || ''} required placeholder="QR nuorodos token reikšmė" /></label><button className="primary-button mt-3">Rasti bilietą</button></form>{token && (!registration || registration.status !== 'reserved') && <p role="status" className="panel text-sm text-amber-200">{unavailable ? 'Bilietų duomenys šiuo metu nepasiekiami.' : 'Bilietas nerastas, atšauktas arba neturi rezervuotos vietos.'}</p>}{registration?.status === 'reserved' && <section className="panel"><p className="text-xs text-amber-200 mb-3">Žaidėjo bilietas</p><h2 className="text-2xl font-semibold">{registration.profiles?.username}</h2><p className="mt-3 text-slate-300">{registration.game_events?.title}</p><p className="mt-2 text-sm text-slate-400">{registration.game_events && formatEventDate(registration.game_events.starts_at)}</p><p className="mt-2 text-sm text-slate-400">Stalas {registration.event_seats?.table_number} · vieta {registration.event_seats?.seat_number}</p><div className="mt-5">{registration.checked_in_at ? <p role="status" className="text-emerald-200 text-sm">Atvykimas jau pažymėtas.</p> : registration.game_events?.status === 'open' ? <MutationButton action={checkInAction.bind(null,registration.checkin_token)}>Patvirtinti žaidėjo atvykimą</MutationButton> : <p className="text-sm text-slate-400">Renginio atvykimo registracija uždaryta.</p>}</div><Link className="block mt-5 text-sm text-amber-200" href={`/admin/events/${registration.event_id}`}>Visi renginio dalyviai →</Link></section>}</div>;
}
