import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { isUuid, eventStatusLabels, formatEventDate } from '@/lib/events';
import { updateEventAction, saveResultAction, publishResultsAction, checkInAction, cancelEventAction } from '@/lib/actions/events';
import { GameEvent, EventRegistration, EventResult } from '@/types/database';
import { ActionForm, LocalDateField, MutationButton } from '@/components/ActionForm';
import { ResultsTable } from '@/components/ResultsTable';

export default async function AdminEventPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; if (!isUuid(id)) notFound();
  const supabase = await createClient(); const { data, error } = await supabase.from('game_events').select('*').eq('id',id).maybeSingle();
  if (error) return <p role="status" className="panel max-w-6xl mx-auto">Renginio duomenys nepasiekiami.</p>;
  if (!data) notFound(); const event = data as GameEvent;
  const [{ data: registrationData, error: registrationError }, { data: resultsData }] = await Promise.all([supabase.from('event_registrations').select('*, profiles(username), event_seats(table_number, seat_number), event_teams(*)').eq('event_id',id).order('created_at'),supabase.from('event_results').select('*').eq('event_id',id)]);
  const registrations = (registrationData || []) as EventRegistration[];
  const active = registrations.filter(r => r.status !== 'cancelled');
  return <div className="max-w-6xl mx-auto px-5 sm:px-8"><Link href="/admin/events" className="text-sm text-slate-400">← Visi renginiai</Link><div className="flex flex-wrap justify-between gap-4 items-start my-6"><div><h1 className="text-3xl font-bold">{event.title}</h1><p className="text-sm text-slate-400 mt-2">{formatEventDate(event.starts_at)} · {eventStatusLabels[event.status]}</p></div><Link className="secondary-button" href={`/events/${id}`}>Viešas renginio puslapis</Link></div>
    <section className="panel mb-8"><h2 className="text-xl font-semibold mb-5">Renginio informacija</h2><ActionForm action={updateEventAction.bind(null,id)}><div className="grid md:grid-cols-2 gap-4"><label className="field-label">Pavadinimas<input name="title" className="field mt-2" defaultValue={event.title} required minLength={2} maxLength={120} /></label><LocalDateField value={event.starts_at} /><label className="field-label">Susitikimo vieta<input name="location" className="field mt-2" defaultValue={event.location} required minLength={2} maxLength={200} /></label><label className="field-label">Būsena<select name="status" className="field mt-2" defaultValue={event.status}>{Object.entries(eventStatusLabels).filter(([key]) => !['completed','cancelled'].includes(event.status) || key === event.status).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label></div><label className="field-label">Aprašymas<textarea name="description" className="field mt-2" rows={3} maxLength={2000} defaultValue={event.description} /></label><p className="text-xs text-amber-200/80">Atšaukus renginį panaikinamos jo rezervacijos ir pakvietimai. Pasibaigusio ar atšaukto renginio iš naujo atidaryti negalima.</p></ActionForm></section>
    <section className="panel mb-8"><div className="flex flex-wrap justify-between gap-3 mb-5"><h2 className="text-xl font-semibold">Dalyviai ir laukiančiųjų eilė</h2><p className="text-xs text-slate-400">Rezervuota: {active.filter(r => r.status === 'reserved').length} · Laukia: {active.filter(r => r.status === 'waiting').length} · Atvyko: {active.filter(r => r.checked_in_at).length}</p></div>{registrationError ? <p role="status" className="text-amber-200 text-sm">Dalyvių duomenys nepasiekiami.</p> : <div className="space-y-3">{active.map(r => <div key={r.id} className="flex flex-wrap items-center justify-between gap-4 border-t border-slate-800 py-4"><div><h3 className="font-medium">{r.profiles?.username || 'Žaidėjas'}</h3><p className="text-xs text-slate-400 mt-1">{r.status === 'waiting' ? 'Laukiančiųjų eilėje' : `Stalas ${r.event_seats?.table_number} · vieta ${r.event_seats?.seat_number}`}{r.event_teams ? ` · ${r.event_teams.name}` : ''}{r.checked_in_at ? ' · Atvykęs' : ''}</p></div><div className="flex flex-wrap gap-2">{r.status === 'reserved' && !r.checked_in_at && event.status === 'open' && <MutationButton action={checkInAction.bind(null,r.checkin_token)}>Pažymėti atvykimą</MutationButton>}{event.status !== 'completed' && <MutationButton action={cancelEventAction.bind(null,id,r.user_id)} confirmMessage={r.event_teams?.owner_id === r.user_id ? 'Atšaukti visos šio kapitono komandos rezervaciją?' : 'Atšaukti šio žaidėjo registraciją?'}>Atšaukti</MutationButton>}</div></div>)}{!active.length && <p className="text-sm text-slate-400">Dalyvių dar nėra.</p>}</div>}</section>
    <section className="panel"><h2 className="text-xl font-semibold mb-5">Žaidimo rezultatai</h2><ResultsTable results={(resultsData || []) as EventResult[]} />{event.status !== 'completed' ? <p className="mt-5 text-sm text-slate-400">Pažymėkite renginį kaip pasibaigusį, kad galėtumėte įvesti ir paskelbti rezultatus.</p> : <div className="mt-6 space-y-6"><ActionForm action={saveResultAction.bind(null,id)} label="Išsaugoti rezultatą"><div className="grid sm:grid-cols-3 gap-4"><label className="field-label">Stalas<select name="table_number" className="field mt-2">{[1,2,3,4,5,6].map(n => <option key={n} value={n}>Stalas {n}</option>)}</select></label><label className="field-label">Komandos pavadinimas<input name="team_name" className="field mt-2" required minLength={2} maxLength={60} /></label><label className="field-label">Taškai<input name="points" className="field mt-2" type="number" required min={0} max={1000000} step={1} /></label></div><p className="text-xs text-slate-400">Įvedus tą patį stalą, jo rezultatas bus atnaujintas.</p></ActionForm><MutationButton action={publishResultsAction.bind(null,id,!event.results_published)}>{event.results_published ? 'Paslėpti rezultatus' : 'Paskelbti rezultatus'}</MutationButton></div>}</section>
  </div>;
}
