'use client';

import { useState, useTransition } from 'react';
import Link from 'next/link';
import { requestPasswordResetAction, resetPasswordAction } from '@/lib/actions/auth';

export function PasswordForm({ reset = false }: { reset?: boolean }) {
  const [pending,start] = useTransition(); const [result,setResult] = useState<{error?:string;message?:string} | null>(null);
  return <section className="panel max-w-md mx-5 sm:mx-auto"><h1 className="text-2xl font-bold">{reset ? 'Naujas slaptažodis' : 'Slaptažodžio atkūrimas'}</h1><p className="text-sm text-slate-400 mt-3 mb-6">{reset ? 'Įveskite naują slaptažodį du kartus.' : 'Įveskite paskyros tikrą el. paštą. Atsiųsime atkūrimo nuorodą.'}</p><form className="space-y-4" onSubmit={e => { e.preventDefault();const data = new FormData(e.currentTarget);setResult(null);start(async () => { try { setResult(await (reset ? resetPasswordAction(data) : requestPasswordResetAction(data))); } catch { setResult({error:'Veiksmas nepavyko. Bandykite dar kartą.'}); } }); }}>{reset ? <>{[{name:'password',label:'Naujas slaptažodis'},{name:'password_confirmation',label:'Pakartokite slaptažodį'}].map(f => <label key={f.name} className="field-label">{f.label}<input className="field mt-2" name={f.name} type="password" autoComplete="new-password" minLength={6} required /></label>)}</> : <label className="field-label">El. paštas<input className="field mt-2" name="email" type="email" autoComplete="email" required maxLength={254} /></label>}<button className="primary-button w-full" disabled={pending}>{pending ? 'Palaukite…' : reset ? 'Pakeisti slaptažodį' : 'Gauti atkūrimo nuorodą'}</button>{result && <p role={result.error ? 'alert' : 'status'} className={`text-sm ${result.error ? 'text-red-300' : 'text-emerald-200'}`}>{result.error || result.message}</p>}</form>{!reset && <p className="mt-5 text-xs text-slate-400">Ankstesnėms paskyroms be tikro el. pašto atkūrimo nuoroda nepristatoma. Kreipkitės į organizatorių.</p>}<Link href="/auth/login" className="block text-sm text-amber-200 mt-5">← Prisijungimas</Link></section>;
}
